export const PRODUCTS = [
  {
    id: "kitchen-decor",
    discount: "24% off",
    title: "Customized Wooden Kitchen Decor",
    price: 650,
    oldPrice: 850,
    img: "/product/11.jpg",
    category: "Wooden Kitchen Decor",
    sku: "kitchen-11",
    status: "In Stock",
  },
  {
    id: "key-holder",
    discount: "14% off",
    title: "Customized Wooden Key Holder",
    price: 1200,
    oldPrice: 1400,
    img: "/product/12.jpg",
    category: "Wooden Key Holder",
    sku: "holder-31",
    status: "In Stock",
  },
  {
    id: "money-box",
    discount: "14% off",
    title: "Customized Wooden Money Saving Box",
    price: 1500,
    oldPrice: 1750,
    img: "/product/13.jpg",
    category: "Wooden Money Saving Box",
    sku: "money-13",
    status: "In Stock",
  },
  {
    id: "chopping-board",
    discount: "14% off",
    title: "Customized Wooden Chopping Board",
    price: 1800,
    oldPrice: 2100,
    img: "/product/14.jpg",
    category: "Wooden Chopping Board",
    sku: "board-14",
    status: "In Stock",
  },
  {
    id: "photo-frame-1",
    discount: "13% off",
    title: "Customized Wooden Photo Frame",
    price: 1050,
    oldPrice: 1200,
    img: "/product/15.jpg",
    category: "Wooden Photo Frame",
    sku: "frame-15",
    status: "In Stock",
  },
  {
    id: "photo-frame-2",
    discount: "21% off",
    title: "Customized Wooden Photo Frame",
    price: 950,
    oldPrice: 1200,
    img: "/product/16.jpg",
    category: "Wooden Photo Frame",
    sku: "frame-16",
    status: "In Stock",
  },
  {
    id: "bookmark-1",
    discount: "25% off",
    title: "Customized Wooden Bookmark",
    price: 150,
    oldPrice: 200,
    img: "/product/17.jpg",
    category: "Wooden Bookmark",
    sku: "mark-17",
    status: "In Stock",
  },
  {
    id: "bookmark-2",
    discount: "25% off",
    title: "Customized Wooden Bookmark",
    price: 150,
    oldPrice: 200,
    img: "/product/18.jpg",
    category: "Wooden Bookmark",
    sku: "mark-18",
    status: "In Stock",
  },
  {
    id: "tray-1",
    discount: "15% off",
    title: "Customized Wooden Tea/Serving Tray",
    price: 850,
    oldPrice: 1000,
    img: "/product/19.jpg",
    category: "Wooden Tea/Serving Tray",
    sku: "tray-19",
    status: "In Stock",
  },
  {
    id: "tray-2",
    discount: "18% off",
    title: "Customized Wooden Tea/Serving Tray",
    price: 820,
    oldPrice: 999,
    img: "/product/20.jpg",
    category: "Wooden Tea/Serving Tray",
    sku: "tray-20",
    status: "In Stock",
  },
];

export const getProductById = (id) => PRODUCTS.find((p) => p.id === id);
